spring:
    application:
        name: Ornitho-server
    data:
        mongodb:
            host: localhost
            port: 27017
            database: ornithodb-test
            
logging:
    level:
        cat.dme.ornitho: TRACE
